(Link)=>
let
    Source = Web.Page(File.Contents(Text.From(Link))),
    Data0 = Source{0}[Data],
    #"Added Columns" = List.Accumulate({Table.ColumnCount(Data0)+1..Table.ColumnCount(Data0)+31}, Data0, (state, current) => Table.AddColumn(state, "Column" & Number.ToText(current), each null))
in
    #"Added Columns"

let
    Source = Excel.CurrentWorkbook(){[Name="Table2"]}[Content],
    #"Removed Blank Rows" = Table.SelectRows(Source, each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Added Index" = Table.AddIndexColumn(#"Removed Blank Rows", "Index", 0, 1, Int64.Type),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Column1"}),
    #"Invoked Custom Function" = Table.AddColumn(#"Reordered Columns", "ResultTable", each getTables([Column1])),
    #"Renamed Columns" = Table.RenameColumns(#"Invoked Custom Function",{{"Column1", "Links"}}),
    #"Expanded ResultTable" = Table.ExpandTableColumn(#"Renamed Columns", "ResultTable", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40"})
in
    #"Expanded ResultTable"

